name: coffee_shop_ui
description: A new Flutter project.
publish_to: "none"

version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1
  google_fonts: ^6.2.1
  intl: ^0.20.1
  readmore: ^3.0.0
  flutter_screenutil: ^5.9.0
  lottie: ^2.6.0
  equatable: ^2.0.7
  flutter_bloc: ^8.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/